spring.application.name=act
# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/m9_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=jiasanchez
spring.datasource.password=postgres
#
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect